openapi: 3.0.0
info:
  title: Mobile Backend API
  description: API documentation for SupaMenu Node.js backend
  version: 1.0.0

servers:
  - url: http://localhost:8000

paths:
  /users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegister"
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Invalid input

  /users/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"
      responses:
        "200":
          description: Login successful
        "401":
          description: Invalid credentials

  /users/me:
    get:
      summary: Get authenticated user's info
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User info returned
        "401":
          description: Unauthorized

  /users/logout:
    get:
      summary: Logout current user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Logout successful

  /products:
    post:
      summary: Create a new product
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "201":
          description: Product created
    get:
      summary: Get all products
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A list of products

  /products/{id}:
    put:
      summary: Update a product
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Product ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Product updated
    delete:
      summary: Delete a product
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Product ID
      responses:
        "200":
          description: Product deleted

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserRegister:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string

    UserLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    Product:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
